# #####################
# # Author: [TrexsMC] #
# #####################
Interval: 60
Prefix: '&a>>>&cAM&a<<<'
Message:
  SuccessfulReload: '&6Has restarted the config successfully'
  NotPermission: '&6There is no right to use this command'
  CommandHelp: '&6Use Command /am reload reload the config.yml'
Messages:
- '&b&lHello everybody'
- '&a&lHello everybody'
- '&c&lHello everybody'
