# ###################################################################################################
#  +----------------------------------------------------------------------------------------------+ #
#  |    _____                       _           _     _           _____       _                   | #
#  |   / ____|                     | |         | |   | |         |  __ \     | |                  | #
#  |  | (___  _   _ _ __   ___ _ __| |     ___ | |__ | |__  _   _| |  | | ___| |_   ___  _____    | #
#  |   \___ \| | | | '_ \ / _ \ '__| |    / _ \| '_ \| '_ \| | | | |  | |/ _ \ | | | \ \/ / _ \   | #
#  |   ____) | |_| | |_) |  __/ |  | |___| (_) | |_) | |_) | |_| | |__| |  __/ | |_| |>  <  __/   | #
#  |  |_____/ \__,_| .__/ \___|_|  |______\___/|_.__/|_.__/ \__, |_____/ \___|_|\__,_/_/\_\___|   | #
#  |               | |                                       __/ |                                | #
#  |               |_|                                      |___/                                 | #
#  |                                                                                              | #
#  |                                                                                              | #
#  |  WIKI:        http://en.wiki.pedrojm96.com/wiki/SuperLobbyDeluxe                             | #
#  |  BUG REPORTS: https://www.spigotmc.org/threads/superlobbydeluxe.132949                       | #
#  |  AUTHOR: PedroJM96 (pedrojm96.com)                                                           | #
#  |  OFFICIAL SERVER: mc.minepal.net                                                             | #
#  |                                                                                              | #
#  +----------------------------------------------------------------------------------------------+ #
# ###################################################################################################
# 
#  +----------------------------------------------------------------------------------------------+ #
#  | For a detailed explanation of the configuration see this page.                               | #
#  | http://en.wiki.pedrojm96.com/wiki/SuperLobbyDeluxe                                           | #
#  +----------------------------------------------------------------------------------------------+ #
Update-Check: true
Prefix: '&6SuperLobby &e>> &7'
Messages: EN
Worlds:
- world
- lobby
- hub
DisableRain: true
DisableBlockBreak: true
DisableBlockPlace: true
DisableBlockBurn: true
DisableDropItem: true
DisableItemMove: true
DisableItemDamage: true
DisablePickUpItems: true
DisableEntityExplode: true
DisableDamage: true
DisableHunger: true
DisableDeathMessage: true
DisableCreatureSpawn: true
ClearDropsOnDeath: true
JoinClearInventory: true
JoinClearChat: true
JoinSpawn: true
CommandSpawn: true
LobbyItems: true
VoidTP: true
VoidLevel: 0
AlwaysDay: true
InfoCommands: true
CustomEvents: true
FrameProtect: true
FarmProtect: true
JumpPads: true
JumpPadsPlateBlock: GOLD_PLATE
JoinBossBar:
  Enable: true
  Message: '&3Chào mừng bạn đến với server!'
  Color: BLUE
  Style: NOTCHED_20
  Seconds: 10
JoinTab:
  Enable: true
  Update: 1000
  Header: |-
    &7
    &a&m--&2&m--&8&m[-&r &a&lYourserver &f&lNetwork &8&m-]&2&m--&a&m--
    &7
  Footer: |-
    &7
    &7Website: &7yourserver.com
    &7Twitter: &7@yourserver
    &7Store: &7store.yourserver.com
    &7
JoinTitles:
  Enable: true
  FadeIn: 20
  Stay: 50
  FadeOut: 10
  Title: '&6<player> &bWelcome to'
  Subtitle: '&6&lYourserver'
JoinMotd:
  Enable: true
  Message:
  - '&f&m+&9&m---------------------------------------------------&f&m+'
  - ' '
  - '&7[&9&l>&7] &6&l<player> &7Chào mừng bạn đến &9&lYourserver &f&lNetwork!'
  - ' '
  - '&7[&9&l>&7]  &7Buy rank on: &2yourpage.com/shop'
  - '&7[&9&l>&7]  &7Facebook: &2facebook.com/Yourserver'
  - '&7[&9&l>&7]  &7Để biết thêm thông tin &2/info'
  - ''
  - '&f&m+&9&m---------------------------------------------------&f&m+'
JoinGameMode:
  Enable: true
  GameMode: survival
CommandsBlacklist:
  Enable: true
  Bypass: superlobby.admin
  List:
  - p
  - pl
  - '?'
  - help
  - plugins
  - bukkit:plugins
  - bukkit:pl
  - bukkit:?
  - bukkit:help
  - ver
  - version
  - gc
  - bukkit:version
  - bukkit:ver
JoinActionBar:
  Enable: true
  Type: Animation
  Messages:
  - 0,&6W_
  - 0,&6We_
  - 0,&6Wel_
  - 0,&6Welc_
  - 0,&6Welco_
  - 0,&6Welcom_
  - 0,&6Welcome_
  - 0,&6Welcome _
  - 0,&6Welcome t_
  - 0,&6Welcome to_
  - 0,&6Welcome to _
  - 0,&6Welcome to m_
  - 0,&6Welcome to my_
  - 0,&6Welcome to my _
  - 0,&6Welcome to my s_
  - 0,&6Welcome to my se_
  - 0,&6Welcome to my ser_
  - 0,&6Welcome to my serv_
  - 0,&6Welcome to my serve_
  - 0,&6Welcome to my server_
  - 0,&6Welcome to my server!_
ChatFormat:
  Enable: true
  format:
    default: '{PREFIX} &r{PLAYER_NAME} &e&l> &7{MESSAGE}'
    vip: '{PREFIX} &r{PLAYER_NAME} &e&l> &5{MESSAGE}'
    admin: '{PREFIX} &r{PLAYER_NAME}% &e&l> &c{MESSAGE}'
