MySQL:
  Enabled: false
  Host: 127.0.0.1
  Port: 3306
  Username: user
  Password: mySecurePassword
  Database: IslandBorder
  TableName: IslandBorder
  SSL: false
ToggleCooldown:
  Enabled: true
  Seconds: 5
Language: EN
